languageCode = "en-us"
title = "Clever Cloud documentation"
theme = "/ace-documentation"
enableRobotsTXT = false
enableEmoji = true
enableGitInfo = true
canonifyURLs = true
Paginate = 100
ignorefiles = ["somethingToIgnore.md"]

[params]
	footerLogo = "images/footer-logo.svg"
	headerLogo = "images/header-logo.svg"
	menuLogo = "images/menu-logo.svg"
	signUpURL = "https://api.clever-cloud.com/v2/sessions/signup" # Configure SignUp link
	editURL = "https://gitlab.corp.clever-cloud.com/clever-cloud/wip-new-doc/edit/master/" # Configure content edition link
	description = "Clever Cloud Documentation"
	author = "Clever Cloud"
	showVisitedLinks = true
	disableBreadcrumb = false
	disableNextPrev = false
	disableInlineCopyToClipBoard = false
	ordersectionsby = "weight"
	disableAssetsBusting = true
	themeVariant = "clever"
	Subdir= true
	disableSearch = false # default is false
	disableReadmoreNav = false # set true to hide prev/next navigation, default is false
	highlightClihighlightClientSideentSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
	menushortcutsnewtab = true # set true to open shortcuts links to a new tab/window
	algolia_appId = "algoliaAppId"
	algolia_apiKey = "algoloaAPIKEY"
	algolia_indexName = "yourAlgoliaIndex"
	contentRepository = "https://github.com/clevercloud/doc.clever-cloud.com/"

[outputs]
    home = ["HTML", "RSS", "JSON","MANIFEST", "Algolia"]

[outputFormats.Algolia]
    mediaType = "application/json"
    baseName = "algolia"
    isPlainText = true
    notAlternative = true
  
[Languages]
    [Languages.en]
        title = "Clever Cloud Documentation"
        weight = 1
        languageName = "English"

        [[Languages.en.menu.shortcuts]] 
            name = "Doc"
            identifier = "doc"
            url = "https://www.clever-cloud.com/doc/"
            weight = 10

    [Languages.fr]
        title = "Documentation de Clever Cloud"
        weight = 2
        languageName = "Français"

        [[Languages.fr.menu.shortcuts]] 
            name = "Doc"
            identifier = "doc"
            url = "https://www.clever-cloud.com/doc/"
            weight = 10

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
    [markup.tableOfContents]
        endLevel = 2
        ordered = false
        startLevel = 2
    [markup.highlight]
            codeFences = true
            guessSyntax = false
            hl_Lines = ""
            lineNoStart = 1
            lineNos = false
            lineNumbersInTable = true
            noClasses = true
            style = "github"
            tabWidth = 4